[debian13]
# Replace with your Debian 13 target host(s)
# debian13-host ansible_host=192.168.1.50 ansible_user=root

[proxmox]
# Replace with your Proxmox host
# pve1 ansible_host=192.168.1.10 ansible_user=root

[arch]
# Replace with your Arch host
# arch1 ansible_host=192.168.1.20 ansible_user=root
arch1 ansible_host=192.168.1.46 ansible_user=liam
